#
# Makefile for EnvTool - Linux Settings
#
# Author: Sam Adams <sea36 at users.sourceforge.net>
#         Unilever Centre for Molecular Science Informatics
#         University Of Cambrige, UK
#

CFLAGS += -fPIC
CXXFLAGS += -I$(JAVA_HOME)/include/linux -fPIC
LDFLAGS += -shared

LIB_PREFIX = lib
LIB_SUFFIX = .so
