#
# Makefile for EnvTool - Windows settings
#
# Author: Sam Adams <sea36 at users.sourceforge.net>
#         Unilever Centre for Molecular Science Informatics
#         University Of Cambrige, UK
#

CXXFLAGS += -I"$(JAVA_HOME)/include/win32"
LDFLAGS += -Wl,--add-stdcall-alias -shared

LIB_PREFIX =  
LIB_SUFFIX = .dll
