/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jnati_envtool_EnvTool */

#ifndef _Included_net_sf_jnati_envtool_EnvTool
#define _Included_net_sf_jnati_envtool_EnvTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jnati_envtool_EnvTool
 * Method:    jniGetEnvVar
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_jnati_envtool_EnvTool_jniGetEnvVar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_jnati_envtool_EnvTool
 * Method:    jniSetEnvVar
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sf_jnati_envtool_EnvTool_jniSetEnvVar
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
